First screen
p-osypov/army pull request #3
Opened 2024-11-05 19:34 UTC by radishevskyi

# 📝 Description

- 

# 🔄 Type of change

- [ ] Cleaning up
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality to something)
- [ ] Configuration change
- [ ] Translation change

# 🧪 How has this been tested / or will it be tested?

- [ ] Manually surfing the app

# ✅ Checklist:

- [ ] My changes generate no new warnings in console or terminal
- [ ] I have performed a self-review of my code
- [ ] I have updated versions of the package.json and package-lock.json

# 🖼️ Result screenshot/video (optional):

# Gif to summarize my emotions (optional):

2024-11-05 23:11 UTC, p-osypov requested changes

2024-11-05 23:11 UTC, p-osypov commented on src/modules/home/first-screen/first-screen.styles.ts
> +    font-size: 18px;
Add css variable --font-size-medium: 1.125rem; /* 18px */
```suggestion
font-size: var(--font-size-medium);
```

2024-11-05 23:11 UTC, p-osypov commented on src/modules/home/first-screen/first-screen.tsx
> +
Create translations for this section

2024-11-05 23:11 UTC, p-osypov commented on src/modules/home/first-screen/first-screen.tsx
> +          <SC.ContactLink href="tel:(209) 555-0104">
Create /src/shared/config.ts with const contacts where we gonna keep all meta information of this project.

2024-11-05 23:11 UTC, p-osypov commented on src/modules/home/first-screen/first-screen.tsx
> +            <Icons.PhoneNum style={{ marginRight: '10px' }} />
Move inline styles to styled-components, or add class icon to these icons and set margin in ContactLink .icon.


-------------
If design has non `--spacing` gap we should ignore it and use `--spacing` that is near to value from design. 
In that case marginRight must be `var(--spacing)`.

2024-11-05 23:11 UTC, p-osypov commented on src/shared/assets/icons/mail.tsx
> +    width="16"
set width and height 20px to all icons by default

2024-11-05 23:11 UTC, p-osypov commented on src/shared/assets/icons/mail.tsx
> +        <stop stop-color="#FAFAFA" />
Colors must be set from props.
```suggest
<stop stopColor={color || "#FAFAFA"} />
```

--------------


Update all icons we have. Check the console, there could be errors related to invalid svg properties.

2024-11-06 19:22 UTC, radishevskyi commented on src/modules/home/first-screen/first-screen.styles.ts
> +    padding-top: calc(106px + var(--spacing-x2));
[fix: styles](https://github.com/p-osypov/army/pull/3/commits/6853d1e7640ca1fba6c6ca3378fea9345322bc58)

2024-11-06 19:22 UTC, radishevskyi commented on src/modules/home/first-screen/first-screen.styles.ts
> +    background: #41534633;
[fix: styles](https://github.com/p-osypov/army/pull/3/commits/6853d1e7640ca1fba6c6ca3378fea9345322bc58)

2024-11-06 19:22 UTC, radishevskyi commented on src/modules/home/first-screen/first-screen.styles.ts
> +    gap: 10px;
[fix: styles](https://github.com/p-osypov/army/pull/3/commits/6853d1e7640ca1fba6c6ca3378fea9345322bc58)

2024-11-06 19:22 UTC, radishevskyi commented on src/modules/home/first-screen/first-screen.styles.ts
> +    font-size: 18px;
[fix: styles](https://github.com/p-osypov/army/pull/3/commits/6853d1e7640ca1fba6c6ca3378fea9345322bc58)

2024-11-06 19:23 UTC, radishevskyi commented on src/modules/home/first-screen/first-screen.tsx
> +
[feat: translation for first-screen](https://github.com/p-osypov/army/pull/3/commits/0a648767a748014f5d1b1d5ad32a3db8ccf464a4)

2024-11-06 19:23 UTC, radishevskyi commented on src/modules/home/first-screen/first-screen.tsx
> +          <SC.ContactLink href="tel:(209) 555-0104">
[feat: created obj contacts](https://github.com/p-osypov/army/pull/3/commits/0851545ecc98bd641064dd0f3456c0895de4853f)

2024-11-06 19:24 UTC, radishevskyi commented on src/modules/home/first-screen/first-screen.tsx
> +            <Icons.PhoneNum style={{ marginRight: '10px' }} />
[fix: logic](https://github.com/p-osypov/army/pull/3/commits/9ded7df66ab5bb9237f6e0d9310e4d7c1a9cdc48)

2024-11-09 14:14 UTC, p-osypov approved these changes

2024-11-09 14:14 UTC, merged