About us
p-osypov/army pull request #5
Opened 2024-11-18 21:20 UTC by radishevskyi

# 📝 Description

- added about us section

# 🔄 Type of change

- [ ] Cleaning up
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality to something)
- [ ] Configuration change
- [ ] Translation change

# 🧪 How has this been tested / or will it be tested?

- [ ] Manually surfing the app

# ✅ Checklist:

- [ ] My changes generate no new warnings in console or terminal
- [ ] I have performed a self-review of my code
- [ ] I have updated versions of the package.json and package-lock.json

# 🖼️ Result screenshot/video (optional):

# Gif to summarize my emotions (optional):

2024-11-20 01:55 UTC, p-osypov requested changes

2024-11-20 01:55 UTC, p-osypov commented on src/modules/home/about-us/about-us.styles.ts
> +  Div1: styled.div`
```suggestion
ImgColumn: styled.div
```

2024-11-20 01:55 UTC, p-osypov commented on src/modules/home/about-us/about-us.styles.ts
> +    min-width: calc(50% - var(--spacing-x3));
Is this needed? It should work without this.

2024-11-20 01:55 UTC, p-osypov commented on src/modules/home/about-us/about-us.styles.ts
> +  Background1Item: styled.div``,
Remove

2024-11-20 01:55 UTC, p-osypov commented on src/modules/home/about-us/about-us.styles.ts
> +    background-color: #415346;
Isn't it an accent color? If yes or it is similar then use css variable

2024-11-20 01:55 UTC, p-osypov commented on src/modules/home/about-us/about-us.styles.ts
> +  Destroyed: styled.p`
```suggestion
Destroyed: styled.span
```

2024-11-20 01:55 UTC, p-osypov commented on src/modules/home/about-us/about-us.styles.ts
> +  Background1: styled.div`
```suggestion
InfoBlock: styled.div
```

2024-11-20 01:55 UTC, p-osypov commented on src/modules/home/about-us/about-us.styles.ts
> +  Background2: styled.div`
```suggestion
ImgBlock: styled.div`
```

2024-11-20 01:55 UTC, p-osypov commented on src/modules/home/about-us/about-us.styles.ts
> +  Background3: styled.div`
```suggestion
ImgBlock: styled.div`
```

2024-11-20 01:55 UTC, p-osypov commented on src/modules/home/about-us/about-us.styles.ts
> +  Div2: styled.div`
```suggestion
TextColumn: styled.div`
```

2024-11-20 01:55 UTC, p-osypov commented on src/modules/home/about-us/about-us.styles.ts
> +    max-width: calc(50% - var(--spacing-x3));
Is this needed? It should work without this.

2024-11-20 01:55 UTC, p-osypov commented on src/modules/home/about-us/about-us.styles.ts
> +    color: #fafafab2;
Use same color we have on first screen. And actually whole website use white color for text so it is enough to set white color for text in body. All children elemens will inherit color so there is no need to set white color for every component.

2024-11-20 01:55 UTC, p-osypov commented on src/shared/components/label/label.tsx
> +  font-size: 12px;
Use css variable if we have it

2024-11-20 01:56 UTC, p-osypov commented
Fill the description and add screenshot of work you made. Desktop and Mobile

2024-11-20 13:44 UTC, radishevskyi commented on src/modules/home/about-us/about-us.styles.ts
> +    background-color: #415346;
[fix: styles](https://github.com/p-osypov/army/pull/5/commits/182f44b38675be57d62bf0cd6bfcd3df0ab32120)

2024-11-20 13:44 UTC, radishevskyi commented on src/modules/home/about-us/about-us.styles.ts
> +  Destroyed: styled.p`
[fix: styles](https://github.com/p-osypov/army/pull/5/commits/182f44b38675be57d62bf0cd6bfcd3df0ab32120)

2024-11-20 13:44 UTC, radishevskyi commented on src/modules/home/about-us/about-us.styles.ts
> +  Background1: styled.div`
[fix: styles](https://github.com/p-osypov/army/pull/5/commits/182f44b38675be57d62bf0cd6bfcd3df0ab32120)

2024-11-20 13:44 UTC, radishevskyi commented on src/modules/home/about-us/about-us.styles.ts
> +  Background2: styled.div`
[fix: styles](https://github.com/p-osypov/army/pull/5/commits/182f44b38675be57d62bf0cd6bfcd3df0ab32120)

2024-11-20 13:44 UTC, radishevskyi commented on src/modules/home/about-us/about-us.styles.ts
> +  Background3: styled.div`
[fix: styles](https://github.com/p-osypov/army/pull/5/commits/182f44b38675be57d62bf0cd6bfcd3df0ab32120)

2024-11-20 13:44 UTC, radishevskyi commented on src/modules/home/about-us/about-us.styles.ts
> +  Div2: styled.div`
[fix: styles](https://github.com/p-osypov/army/pull/5/commits/182f44b38675be57d62bf0cd6bfcd3df0ab32120)

2024-11-20 13:44 UTC, radishevskyi commented on src/shared/components/label/label.tsx
> +  font-size: 12px;
[fix: styles](https://github.com/p-osypov/army/pull/5/commits/182f44b38675be57d62bf0cd6bfcd3df0ab32120)

2024-11-21 02:26 UTC, p-osypov requested changes

2024-11-21 02:26 UTC, p-osypov commented on src/modules/home/first-screen/first-screen.styles.ts
> +    ${mediaWidth('max', 'md')} {
Remove

2024-11-21 11:38 UTC, radishevskyi commented on src/modules/home/first-screen/first-screen.styles.ts
> +    ${mediaWidth('max', 'md')} {
[fix: styles](https://github.com/p-osypov/army/pull/5/commits/5c68731fa194332f8b1d88c2e874c342b0071d23)

2024-11-21 14:01 UTC, p-osypov approved these changes

2024-11-21 14:02 UTC, merged