Our values
p-osypov/army pull request #6
Opened 2024-11-21 16:46 UTC by radishevskyi

# 📝 Description

- added our values section

# 🔄 Type of change

- [ ] Cleaning up
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality to something)
- [x] Configuration change
- [x] Translation change

# 🧪 How has this been tested / or will it be tested?

- [ ] Manually surfing the app

# ✅ Checklist:

- [x] My changes generate no new warnings in console or terminal
- [x] I have performed a self-review of my code
- [ ] I have updated versions of the package.json and package-lock.json

# 🖼️ Result screenshot/video (optional):
![image](https://github.com/user-attachments/assets/1a47bd8e-fcb1-41e4-bd48-0f5cce06a000)

# Gif to summarize my emotions (optional):

2024-11-21 17:26 UTC, p-osypov requested changes

2024-11-21 17:26 UTC, p-osypov commented on src/modules/home/our-values/our-values.styles.ts
> +  Title: styled.h1`
Only one h1 can be on page, and you already have it in AboutUs section.

2024-11-21 17:26 UTC, p-osypov commented on src/modules/home/our-values/our-values.styles.ts
> +    max-width: 40%;
Set px instead ща %

2024-11-21 17:26 UTC, p-osypov commented on src/modules/home/our-values/our-values.styles.ts
> +    max-width: 31%;
Change it to flex 1 instead of max-width

2024-11-21 17:26 UTC, p-osypov commented on src/modules/home/our-values/our-values.styles.ts
> +  BlockTitle: styled.h2`
styled.span

2024-11-25 10:00 UTC, radishevskyi commented on src/modules/home/our-values/our-values.styles.ts
> +  Title: styled.h1`
[fix: styles](https://github.com/p-osypov/army/pull/6/commits/728e8c84bfbc999ea4c82254285accd5088b88f8)

2024-11-25 10:00 UTC, radishevskyi commented on src/modules/home/our-values/our-values.styles.ts
> +    max-width: 40%;
[fix: styles](https://github.com/p-osypov/army/pull/6/commits/728e8c84bfbc999ea4c82254285accd5088b88f8)

2024-11-25 10:00 UTC, radishevskyi commented on src/modules/home/our-values/our-values.styles.ts
> +    max-width: 31%;
[fix: styles](https://github.com/p-osypov/army/pull/6/commits/728e8c84bfbc999ea4c82254285accd5088b88f8)

2024-11-25 10:00 UTC, radishevskyi commented on src/modules/home/our-values/our-values.styles.ts
> +  BlockTitle: styled.h2`
[fix: styles](https://github.com/p-osypov/army/pull/6/commits/728e8c84bfbc999ea4c82254285accd5088b88f8)

2024-12-01 00:04 UTC, p-osypov approved these changes

2024-12-01 00:04 UTC, merged