Analytics
p-osypov/army pull request #8
Opened 2024-12-09 20:00 UTC by radishevskyi

# 📝 Description

- added section analytics

# 🔄 Type of change

- [ ] Cleaning up
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality to something)
- [x] Configuration change
- [x] Translation change

# 🧪 How has this been tested / or will it be tested?

- [ ] Manually surfing the app

# ✅ Checklist:

- [x] My changes generate no new warnings in console or terminal
- [x] I have performed a self-review of my code
- [x] I have updated versions of the package.json and package-lock.json

# 🖼️ Result screenshot/video (optional): 
![image](https://github.com/user-attachments/assets/75fa725e-8f67-4cd3-be84-54cf6bdd6889)

# Gif to summarize my emotions (optional):

2024-12-11 00:15 UTC, p-osypov requested changes
Finish adaptive design. 
Make the cards same height in a line. 
Reduce font size and gaps for tablet/mobile
<img width="1057" alt="Screenshot 2024-12-10 at 19 12 09" src="https://github.com/user-attachments/assets/aaef1ba2-3294-4237-9a65-dc2bcd52d8fa">
<img width="1431" alt="Screenshot 2024-12-10 at 19 07 32" src="https://github.com/user-attachments/assets/f2dd4cc4-a8df-4b62-bf0a-7cc9bb9b46f1">
<img width="556" alt="Screenshot 2024-12-10 at 19 03 33" src="https://github.com/user-attachments/assets/38b84d4c-10ba-44cc-a6d5-e06894e4734d">

2024-12-11 00:15 UTC, p-osypov commented on src/modules/home/analytics/analytics.styles.ts
> +    background-image: var(--text-background-gradient);
If this patter is duplicated many times then it should be separate component.
Create a component Title under components folder. Update other titles that having these styles

2024-12-11 00:15 UTC, p-osypov commented on src/modules/home/analytics/analytics.styles.ts
> +    min-width: 562px;
This can't be flexible. Update media styles

2024-12-12 19:26 UTC, radishevskyi commented on src/modules/home/analytics/analytics.styles.ts
> +    background-image: var(--text-background-gradient);
[fix: styles](https://github.com/p-osypov/army/pull/8/commits/e7044702eb2b08bd467879e1a2b4171b43251598)

2024-12-12 19:26 UTC, radishevskyi commented on src/modules/home/analytics/analytics.styles.ts
> +    min-width: 562px;
[fix: styles](https://github.com/p-osypov/army/pull/8/commits/e7044702eb2b08bd467879e1a2b4171b43251598)

2024-12-16 16:48 UTC, p-osypov approved these changes

2024-12-16 16:48 UTC, merged